version: "3.3"
services:
  postgres_db:
    container_name: postgres_container
    image: postgres:14.3
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "pgdata"
    volumes:
      - ./postgres:/postgres
    ports:
      - "${DB_PORT}:5432"
    expose:
      - "${DB_PORT}"
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:6.9
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - postgres

networks:
  postgres:
      driver: bridge